config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bank_accounts, only: %i[index new create destroy]
  resources :transactions, only: %i[new create]

  namespace :admin do
    resources :users
    resources :dashboards, only: [:index]
    resources :keys, only: [:index, :destroy]
    resources :bank_accounts, only: [:index]
    root 'dashboards#index'
  end

  # Defines the root path route ("/")
  root 'welcome#index'
  get '/admin', to: 'dashboard#index'
end

app/controllers/admin/keys_controller.rb
module Admin
  class KeysController < ApplicationController
    def index
      @keys = User.all.map { |user| UserDataKey.create(user) }.compact
    end

    def destroy
      key_id = BSON::Binary.from_uuid(params[:id])
      User.client_encryption.delete_key(key_id)
      redirect_to admin_keys_path
    end
  end
end

app/views/admin/keys/index.html.erb
<div class="container my-3 text-center">
  <table class="table">
    <thead>
    <tr>
      <th scope="col">User</th>
      <th scope="col">Key Id</th>
      <th scope="col">Key Alt Names</th>
      <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <% @keys.each do |key| %>
      <tr>
        <td><%= key.user_email %></td>
        <td><%= key.key_id.to_uuid %></td>
        <td><%= key.key_alt_names.join(', ') %></td>
        <td><%= link_to "Delete", admin_key_path(key), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>