config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :bank_accounts, only: %i[index new create destroy]
  resources :transactions, only: %i[new create]

  namespace :admin do
    resources :users
    resources :dashboards, only: [:index]
    resources :keys, only: [:index, :destroy]
    resources :bank_accounts, only: [:index]
    root 'dashboards#index'
  end

  # Defines the root path route ("/")
  root 'welcome#index'
  get '/admin', to: 'dashboard#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceLock</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= javascript_importmap_tags %>
    <style>
    body {
      display: flex;
      flex-direction: column;
      align-items: center;
      padding-top: 20px;
    }
    .main-content {
      width: 80%;
    }
  </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light main-content">
      <%= link_to 'FinanceLock', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Overview', bank_accounts_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Add Transaction', new_transaction_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Add Account', new_bank_account_path, class: 'nav-link' %>
          <li class="nav-item">
            <%= link_to 'Admin', admin_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %>
        </ul>
      </div>
    </nav>

    <div class="main-content">
      <% flash.each do |_type, msg| %>
        <div class='alert alert-primary' role='alert'>
          <%= msg %>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>